### ISSUE TITLE
[SUGGESTION] Implement love.filesystem.mount

### ISSUE THREAD

**Issue by ajusa** [TurtleP/LovePotion#104]
[love.filesystem.mount](https://love2d.org/wiki/love.filesystem.mount) allows a game to read a zip file as if it were a folder, without requiring the extraction of a lot of assets. 

My use case has a zip file with about 10,000 files inside of it, where copying to a microsd card is extremely slow. With mount, I should be able to read a file within a zipped version of the directory without having to unzip the entire thing, or store the entire folder in memory.
(For now I'm just using folders instead of a zip file, but it takes around 30 minutes for me to copy it to an SD card.)
Let me know if you need more information!
EDIT: Not sure why the bug label was added here, ignore that

**Comment by TurtleP** [comment]
I've been looking into this for some time, although haven't found anything I can do for it. However, I'll try talking to the maintainers for libctru and libnx to see if something can be done.

**Comment by TurtleP** [comment]
Implemented with #108
