### ISSUE TITLE
[BUG] love.filesystem.createDirectory not consistent with Love2D

### ISSUE THREAD

**Issue by ajusa** [TurtleP/LovePotion#105]
The issue is that love.filesystem.createDirectory appears to create a directory anywhere, when in reality it should be constrained to just the save folder. 

For example, if I run `love.filesystem.createDirectory("/novels")` it will create it on the root of the SD card. However, the value for `love.filesystem.getSaveDirectory()` is `/switch/LovePotion` when I am running my code through the "game" folder. So, the directory should have been made at `/switch/LovePotion/novels` rather than the root of the SD card.

https://love2d.org/wiki/love.filesystem

Let me know if you need more information.

**Comment by TurtleP** [comment]
Fixed with #108
