### ISSUE TITLE
[GUIDE] How to use joystick/gamepad

### ISSUE THREAD

**Issue by hxhieu** [TurtleP/LovePotion#107]
Hi,

So I am trying to get the joystick/gamepad direction on `love.update(dt)`, I need to tell if the directional **is held down** per frame.

The `love.gamepadpressed` only triggers once, doesn't it? or I have missed anything here?

Thanks,
H

**Comment by hxhieu** [comment]
Ok so I have managed to use a `bool` flag and set it on `love.gamepadpressed` and `love.gamepadreleased` accordingly, then just need to check for that flag on `love.update`

But now the question is - how could I detect the joycons event? Trying to find any relevant docs but no luck.

**Comment by TurtleP** [comment]
What version are you even using? It’s best to currently use prerelease 2.

Aside from that, you can get the joystick from`love.joystick.getJoysticks()`. This returns a table of what exists and then check `joystick:isGamepadDown(name)` during the love.update method.
