### ISSUE TITLE
[BUG] Joystick:isGamepadDown only fires once instead of continuously when the button is pressed 

### ISSUE THREAD

**Issue by Nehemek** [TurtleP/LovePotion#121]
When using the function Joystick:isGamepadDown to check for wether a button is pressed or not it only returns true for one "tick/frame" instead of continuously. The function should return true for as long as the button is pressed just like how Joystick:isDown does.

Issue tested on:
System: 3ds v11.14.0-46U
CFW: Luma v10.2.1
Method of execution: Homebrew App
LÖVE Potion version: 2.0.0

**Comment by TurtleP** [comment]
Fixed with commit 689aa40
