### ISSUE TITLE
[BUG] Calling love.graphics.reset() or love.graphics.setCanvas() without arguments does not stop drawing to the last set canvas.

### ISSUE THREAD

**Issue by Phoenix-Flare** [TurtleP/LovePotion#122]
When drawing to a canvas using either Canvas:renderTo() or love.graphics.setCanvas(), the canvas remains set even after a call to love.graphics.reset() or an argumentless call to love.graphics.setCanvas(). These calls do, however, re-enable drawing to the actual screen.

Issue tested on:
System: 3ds v11.14.0-46U
CFW: Luma v10.2.1
Method of execution: Homebrew App
LÖVE Potion version: 2.0.0

**Comment by TurtleP** [comment]
Seems to be fixed with commit 4d74ad0 (from @Nehemek's testing)
