### ISSUE TITLE
[BUG] Require non existant file causes a system crash

### ISSUE THREAD

**Issue by Nehemek** [TurtleP/LovePotion#123]
When using the require statement, if you provide an invalid file path (if it doesn't exist) it causes an Arm11 exception console crash.

System: 3ds v11.14.0-46U
CFW: Luma v10.2.1
Method of execution: Homebrew App
LÖVE Potion version: 2.0.0

**Comment by TurtleP** [comment]
Okay, so this is a weird one. From debugging with you, it seems that the actual problem entails crashing the text drawing function in citro2d. I have no idea why this is happening -- but I have a *vague* notion. This will require a bit more messing around with the area of code it deals with (logging n such) and perhaps going over it with @piepie62 to see if there's something I'm doing wrong.

**Comment by TurtleP** [comment]
I also forgot to mention that this, according to the logs we had, was crashing twice or something (or just not crashing properly at all). It *should* bring up the "BSOD" error screen instead.

**Comment by TurtleP** [comment]
fixed in commit d638726
