### ISSUE TITLE
[BUG] love.graphics.arc has visual glitches or doesn't work at all

### ISSUE THREAD

**Issue by Nehemek** [TurtleP/LovePotion#126]
When using love.graphics.arc() without the last segment argument a circle will be drawn and the "cut out" part is sometimes not drawn or is a jumbled mess (a lot of random triangles), I was unable to figure out what exactly altered the shape.

When using the function WITH the last argument for segments nothing appears to be drawn at all. 

System: 3ds v11.14.0-46U
CFW: Luma v10.2.1
Method of execution: Homebrew App
LÖVE Potion version: 2.0.0

**Comment by TurtleP** [comment]
Something to go over with @piepie62  -- they helped me with this code.

**Comment by TurtleP** [comment]
this was fixed in commit 3978ab5c8bfed77a798dc61009ff9419a4e16819
