### ISSUE TITLE
Ability to turn on/off the 3D on the 3ds

### ISSUE THREAD

**Issue by Nehemek** [TurtleP/LovePotion#129]
**Is your feature request related to a problem? Please describe.**
Love2d (and thus LovePotion) is a 2d engine which means that for certain perspectives it can be really hard to make use of the system's 3d without resorting to what developers would call "fake 3d" (software calculations that output something that resemble 3d without making use of actual 3d accelerated hardware a.k.a meshes and shaders). Examples of these perspectives are top down, isometric and 2.5d.

**Describe the solution you'd like**
A function to enable or disable the 3d in real time. A configuration  could also work but would not be as ideal (see the Pokemon games which enabled and disabled 3d on the fly).

**Describe alternatives you've considered**
When turning the 3d on an option you have is to draw everything twice for both sides. If you don't do this then the image would appear to be fading or transparent due to one eye not seeing anything.

However this poses an obstacle and that is performance. Drawing everything twice means slashing in half the amount of things that can be rendered in a frame.

A solution to this issue would be to use a canvas, render once to the canvas and then render the canvas twice. This would circunvent the performance problems but canvases appear to have some issues with alpha blending which at this point is unknown wether they are related to how to work or a bug itself (needs more testing).

**Additional context**
Even if the last canvas solution could work, a game that does not make use of the 3d and is just rendering a flat image while the 3d is on feels "unpolished". Disabling it would make it appear more thoughtfully created.

**Comment by TurtleP** [comment]
This is definitely something I've been trying to look into. I initially wanted to have this be tied to the `conf.lua` file, since I don't see why you might want to call `love.graphics.setStereoscopic3DEnabled(booll)` in real-time. I'm not saying that it's a bad idea, I want to know why doing it dynamically like you said is useful vs the configuration flag.

**Comment by Nehemek** [comment]
The pokemon games had this thing were the overworld would disable the 3d and only in the battles would it be enabled. I personally found this quite unpolished but eh, it just means it is not a requirement for the system to define it before launching.

Maybe your overworld is top down and your "battle screen" is sideways, or something and viceversa. It's more a _power to the user_ thing I suppose.

**Comment by TurtleP** [comment]
definitely a fair argument, I can add the function, I just need to figure out how to deal with the rendertargets then, since there's only supposed to be two instead of three with it off. It shouldn't be over complex, but it will require investigation.

**Comment by TurtleP** [comment]
added in commit cfddcd5
