### ISSUE TITLE
[BUG] Ellipses have wrong scale and are not centered.

### ISSUE THREAD

**Issue by Nehemek** [TurtleP/LovePotion#130]
### **Describe the bug**
When using love.graphics.ellipse() two glitches happen:
1. Their drawing is not centered, instead their origin appears to be the top left corner.
2. Their scale seem to be round .25 of their true size. For example, using radii of 100 will yield an ellipse more or less of 25 pixels.

### **Expected behavior**
Ellipses should be centered and have proper scale.

### **Relevant Code To Reproduce**
The ellipse and the circle should align, see screenshot below.
```
love.graphics.ellipse("fill",200,120,100,100)
love.graphics.circle("line",200,120,100)
```

### **[Screenshots]**
![ellipses](https://user-images.githubusercontent.com/66986051/113365288-ff7cde80-9312-11eb-82cc-fc6af9a863ae.png)

### **System Info [Please complete the following information]:**
System: 3ds v11.14.0-46U
CFW: Luma v10.2.1
Method of execution: Homebrew App
LÖVE Potion version: ? (This issue is present on an unreleased build used to test the bugfix for transformations of circles).

**Comment by TurtleP** [comment]
fixed in commit 9d61c77
