### ISSUE TITLE
Unable to Compile current build

### ISSUE THREAD

**Issue by CrownFox** [TurtleP/LovePotion#21]
I'm having trouble getting the current build to compile. I've followed the directions from the Wiki, but when I build it apparently has trouble finding SDL2, as the screenshot I've included shows that SDL.h isn't found. Any idea what it is I'm doing wrong?

![mintty_2018-05-13_18-08-27](https://user-images.githubusercontent.com/29871941/39973811-c15d86f0-56d8-11e8-9a61-ed873ffb5c3a.png)

**Comment by TurtleP** [comment]
@CrownFox update your libnx install to the latest git one, it'll resolve this. It *might* also refer to hidGetControllerType as undefined or something, in which I'll do a quick code push to solve it 👍

**Comment by CrownFox** [comment]
Do you mean the 1.1.0 release? I copied over the files for the 1.1.0 release and tried again, but I'm still getting the same issue, SDL.h: No such file or directory

**Comment by TurtleP** [comment]
nope, you want to use git to clone the repo and run `make install` in the libnx directory

**Comment by CrownFox** [comment]
Got it, I'll give that a shot and report back.

**Comment by CrownFox** [comment]
Well, we got further now, but a new error has been encountered.

![mintty_2018-05-13_19-09-23](https://user-images.githubusercontent.com/29871941/39975056-39c00ffc-56e1-11e8-93b8-5d83a150fe82.png)

**Comment by TurtleP** [comment]
You'll need to use devkitpro-pacman to install all sdl2 packages and most of those will be auto-install some of the others as dependencies.  You'll also want `switch-tools`, `general-tools`, and `devkitA64` packages installed. If it complains about the files for those packages existing already, run it with --force, e.g. `dkp-pacman -S --force <package-name>`

**Comment by TurtleP** [comment]
if you run pacman -Syyu it will sync the packages database, then list them with -Sl and they should be there :)

(Also sorry I didn't know Windows uses just `pacman`, since I use WSL/Linux)

**Comment by CrownFox** [comment]
Oh, no worries! I'll get started on that then. I am having an issue with downloading some of the database, as parts of it are slowing down so bad that it stops, while others download in a split moment with no problem. This might take a while, lol

**Comment by TurtleP** [comment]
Yeah it happened to me the other day as well. ¯\_(ツ)_/¯

**Comment by CrownFox** [comment]
That did something! A lot of something, actually. Now I have, yet again, a new error!

![mintty_2018-05-13_19-48-34](https://user-images.githubusercontent.com/29871941/39976087-b13bebc8-56e6-11e8-8058-2186b2f81b22.png)

**Comment by TurtleP** [comment]
what the--when did I put that there..? I'll check my source real quick

**Comment by TurtleP** [comment]
compiles fine for me.. pretty sure these files are in libnx

**Comment by CrownFox** [comment]
I'm not sure. I navigate to C:/devkitpro/libnx/release/ and socket.o is there

**Comment by TurtleP** [comment]
looking into this issue, might be a dumb thing I did from 3DS..

**Comment by TurtleP** [comment]
well, I dunno what could be wrong on your end, but I'm gonna be doing the 1.0.0 release either tonight or tomorrow anyways.

**Comment by CrownFox** [comment]
No worries. I'm like 99% sure it's because I have no idea what I'm doing and there isn't a tutorial out there to give me direction, lol.

I'll wait for release!

**Comment by TurtleP** [comment]
Sorry I couldn't resolve it, but yeah that's the best bet :)

I'll go ahead and close this now. Also if you want to join my discord: https://discord.gg/ggbKkhc
