### ISSUE TITLE
[Bug]: 3.0.1: Basic "Hello World" Regression

### ISSUE THREAD

**Issue by idanmiara** [TurtleP/LovePotion#227]
### Software Version

3.0.1

### What Happened?

Trying to run Love Potion 3.0.1 with any game (i.e. provided Hello World sample) fails: `The software was closed because an error occurred`
It does work with Love Potion 2.4.1

### What was Expected?

The sample program should work like in v3.0.1 like it works in 2.4.1

### Code to Reproduce
extract the 3.0.1 switch release (nro+elf files) to `/switch/lovepotion/` and put the following sample in `/switch/lovepotion/game/main.lua`:

```Lua
function love.draw()
    love.graphics.print("Hello World!", 200, 100)
end
```
run `Love Potion` from the Home Brew menu (game overload method)

zipping it into an individual `hello.love` and running it yields the same results (works in 2.4.1, fails in 3.0.1)

### Console

Nintendo Switch

### Firmware Version(s)

18.0.1

### Custom Firmware Version

AMS 1.7.0

### Execution Method

Homebrew Menu

### Code of Conduct

- [X] I have read the Code of Conduct and agree to these terms

**Comment by TurtleP** [comment]
Could you run the debug version from this last GitHub Action for 3.0? It might help, as I use the debug versions of libraries for these. On top of that, I believe atmosphere should have dumped a log file onto your sd card. If you could provide that as well it would help with debugging.

**Comment by idanmiara** [comment]
@TurtleP Thanks for the super fast response!
Nintendo Switch (Debug)-dc59e91.zip - works!
Nintendo Switch-dc59e91.zip - doesn't work - here's the Atmosphere crash report:
https://drive.google.com/file/d/1XDNzxha8a4tLgpho80s0exHCegyrkVxZ/view?usp=sharing

**Comment by TurtleP** [comment]
Okay, looking at the debug output I got, seems something is wrong when the Event module is converting Joystick events.. which is weird. I thought I had made a fix for some stuff recently, but maybe not committed it into main.

Either way I'll try my best to look into it, been busy working on 3.1.0. Though.. I think this is a similar issue I ran into during work on 3.1.0, so should be easy to fix.

**Comment by TurtleP** [comment]
Okay, 3DS had the fix which is good. I must have forgotten to apply that to the other consoles as well, so there. GitHub Actions is failing which shouldn't be happening.. so give me a moment to figure *that* out.. once it's built you can try the new deployed binaries.

**Comment by TurtleP** [comment]
Okay, fixed up GitHub Actions, needed to do a small tweak to boot.lua due to trying to set up custom certs which is no longer necessary. It should work fine now, once it finishes. Let me know how it goes.
