### ISSUE TITLE
3ds Updates.

### ISSUE THREAD

**Issue by JoeJoeTV** [TurtleP/LovePotion#23]
Will there still be updates for the 3ds version and maybe support for canvase and multiple screens in the future?

**Comment by TurtleP** [comment]
Perhaps. I definitely want both code bases up to date with one another. Theres only a few differences,  and they're quite small. As for canvases, yeah I want to add them. Wasn't sure how they were done initially, but I think I can do it now. 

Drawing to two screens has always been possible, just call love.graphics.setScreen(screen) in your draw function. The parameter, screen, is a string either "top" or "bottom".

**Comment by TurtleP** [comment]
Working on that codebase rework, so this will be closed now 👍
