### ISSUE TITLE
Unable to call love.graphics.setLineWidth()

### ISSUE THREAD

**Issue by tallbl0nde** [TurtleP/LovePotion#24]
When attempting to call this function lovepotion returns the following error:
`attempt to call field 'setLineWidth' (a nil value)`

**Comment by TurtleP** [comment]
I definitely remember that I kept trying to remind myself to add it. I think there's an SDL function for this *somewhere*. I'm currently busy with IRL work, but if anyone makes a PR, they're free to do so 👀

**Comment by TurtleP** [comment]
Next commit implements this and getLineWidth
