### ISSUE TITLE
System Crash on new pre-release, Error Message on videah build

### ISSUE THREAD

**Issue by 16BitWonder** [TurtleP/LovePotion#3]
Hiya! Just would like to say I really like that you're continuing LovePotion, but I did run into a problem earlier with your recent build.

I ran into a pesky problem earlier where I was trying to load an image "cursor3x3.png" from a folder "Common" as follows.

cursor = love.graphics.newImage('Common/cursor.png') <-- (Yes I misspelled it as 'cursor.png', that was the problem)

Whenever I booted the new pre-release version with this mistake, my system crashed and spat out a luma dump.

However with the old videah build I was properly given the line where the error occurred, and that it had failed to create an image.

Not sure how much this helps at all, but hopefully it can assist with improving the error handler so that the system won't crash.

**Comment by TurtleP** [comment]
Yeah, I can fix that. I've also got to improve invalid function call names. Thanks for letting me know and I'm gonna look at doing this today (sorry for the late reply)

**Comment by 16BitWonder** [comment]
No worries, although I might also add that I noticed another bug with fonts.

Doing the following in the videah build works, but in the new pre-release it prints this to the screen;
"Error: Could not load font. Config does not exist"
font = love.graphics.newFont("Common/eightbit.ttf", 10) <-- (This is what threw it)

Furthermore, trying to use the setFont command crashes the program when the previous error is present. (Only in the new pre-release)
love.graphics.setFont(font)

**Comment by notQuiteApex64** [comment]
fonts now use json-s, and there's no need to add the extension ("Common/eightbit")

**Comment by TurtleP** [comment]
Yeah. I have it in the Wiki. You need to use fontbuilder (which is on GitHub) and the fntcnv.py provided with python2:

`python2 fntcnv.py font.fnt font.json` and copy-paste the json and png files to where you want.

**Comment by 16BitWonder** [comment]
Ah, my bad. Thanks for the heads up!
