### ISSUE TITLE
 3ds ver ,Failed to open the PNG file in the directory. use Citra

### ISSUE THREAD

**Issue by historyme** [TurtleP/LovePotion#32]
3ds ver ,Failed to open the PNG file in the directory. use Citra.
only build inside *.3dsx ?

**Comment by TurtleP** [comment]
This function works fine. The newer builds require you to build the 3dsx from the elf file. See [here](https://github.com/TurtleP/LovePotion/wiki/Packaging-Your-Game). Also there’s a 1.1.0-b1.1 build which fixed an issue with romfs loading, so please make sure you use that.

**Comment by historyme** [comment]
I try to display a 1280*720 picture on 3DS. 
It doesn't work.
So,I have to change the resolution of the picture to 400*240, yes, it works.

The problem is that it is incompatible with high-resolution images. For example, 1280*720

**Comment by TurtleP** [comment]
The maximum resolution it can be is 1024x1024 (as a power of 2, internally). If this was from the simplegfx example I'm planning to fix this with a proper example for 3DS.
