### ISSUE TITLE
Errors in any conf.lua aren't reported and appear to freeze up the application.

### ISSUE THREAD

**Issue by NotQuiteApex** [TurtleP/LovePotion#36]
Something I stumbled upon. Basically, any error that happens when loading conf.lua or running love.conf goes unreported while running the boot.lua script, and ends up preventing the application from fully loading.

I haven't tested if it locks the application up entirely, preventing anything continuing to happen (ie another frame to pass in the main loop) or if it just prevents the main love functions from loading and thus softlocks the whole thing. Either way, wrapping the boot script or the love.conf loading and executing in an xpcall and properly reporting the error should fix it.

**Comment by NotQuiteApex** [comment]
Did some further investigation.

For starter's: use more local variables in your boot script!

I looked and did see that the require for conf.lua was pcall wrapped but its error is not properly reported, this should be changed. Also, when calling love.conf, that should also be pcall or xpcall wrapped to catch any errors that may arise during execution (such as trying to access the window table of the input "t" which exists on PC but not on 3DS), which should also be properly reported.

**Comment by TurtleP** [comment]
Alright I decided we should just fix it now. On Switch.

Relevant commit for the future on 3DS:  cd88586
