### ISSUE TITLE
errhand doesn't completely stop program

### ISSUE THREAD

**Issue by notquiteapex** [TurtleP/LovePotion#4]
When LP encounters an error, the program doesn't completely stop. This causes other problems too, as trying to access other lua files when an error is initially encountered, it creates more errors with it but doesn't allow access to other files.
[Example](https://i.imgur.com/SOUya3R.png)

**Comment by TurtleP** [comment]
It might be because of how I made the error handler try to act more like Love's. I'll investigate. Sorry for the late reply.

**Comment by TurtleP** [comment]
This will be resolved with 1.10
