### ISSUE TITLE
love.graphics.draw does not behave according to specification

### ISSUE THREAD

**Issue by NoahRoseLedesma** [TurtleP/LovePotion#41]
In the love documentation for [love.graphics.draw](https://love2d.org/wiki/love.graphics.draw), the scale factor for Y 'sy' defaults to the scale factor for x 'sx'.

However, when using love potion 'sy' is does not seem to default to 'sx', rather both parameters have to be specified for a uniform scaling.

**Comment by TurtleP** [comment]
Fixed with 5d86a26 👍
