### ISSUE TITLE
Transformation stack not being applied to love.graphics.circle 

### ISSUE THREAD

**Issue by NoahRoseLedesma** [TurtleP/LovePotion#44]
Drawing using love.graphics.circle doesn't use transformations defined by the transformation stack (see love.graphics.push and love.graphics.pop).

Here is [an example script](https://gist.github.com/NoahRoseLedesma/85ebea555cd4811623457ba3993920ea) which highlights this error.

**Comment by TurtleP** [comment]
I might have forgotten to call the transform function on its coordinates, simple fix really. If it's not that.. uh.. I dunno ¯\_(ツ)_/¯

I might get to it later if you don't open a pr for it.

**Comment by NoahRoseLedesma** [comment]
Im planning on opening a PR for it. I have the fix in mind, I just need to get my development environment sorted out

**Comment by NoahRoseLedesma** [comment]
This problem is solved for circle but may still exist in other draw functions. I didn't take a close look, but when skimming through graphics.cpp it looked as if a few draw functions were not using the transformation stack.

Further investigation is warranted

**Comment by TurtleP** [comment]
Fixed with the latest commit
