### ISSUE TITLE
"SL" and "SR" button events are not captured by gamepadpressed and gamepadreleased

### ISSUE THREAD

**Issue by NoahRoseLedesma** [TurtleP/LovePotion#46]
Title pretty much explains it all, I have a suspicion that this has yet to be implemented as a solution to distinguish between right and left joycon would need to be made, and adopted as convention.

**Comment by TurtleP** [comment]
The pull request has been merged in SDL2, but we still need to test this. The main issue right now is the naming of buttons. Having them all as "sl" and "sr" isn't easily distinguishable, unless perhaps you use `joystick:getName()` which would return "Joycon", "Left Joycon", or "Right Joycon". Alternate names for the buttons to distinguish these easier are welcome :)

**Comment by TurtleP** [comment]
They will now be captured when the Joy-Con are split, but they must be using horizontal orientations. Please have a look at #55 :)
