### ISSUE TITLE
Switch error log being created as switchlog.txt

### ISSUE THREAD

**Issue by meeces2911** [TurtleP/LovePotion#48]
The Switch error log is being created as switchlog.txt instead of switch/log.txt

This happens with 1.0.3 and the latest doozer build.

**Comment by TurtleP** [comment]
I know where to fix it, it’s in fikesystem.cpp. Specifically getting the save directory. 

I don’t remember if my local files changed at all recently (busy with work) but essentially just adding a slash to the end of it would fix this.

(Figured id post the possible fix before I sleep so I also don’t forget that :P)

**Comment by TurtleP** [comment]
Fixed as of a few commits ago 👍
