### ISSUE TITLE
filesystem.enumerate not Implemented

### ISSUE THREAD

**Issue by RealDekkia** [TurtleP/LovePotion#62]
I tried to get Mari0 (http://stabyourself.net/mari0) on the  Switch. Sadly it uses filesystem.enumerate, which seems to not be implemented

Log:
main.lua:13: attempt to call field 'enumerate' (a nil value)

Traceback

boot:238: in function 'enumerate'
./main.lua:13: in function <./main.lua:10>
[C]: in function 'xpcall'

Love Potion 1.1.0 (API 11.1.0)

Date and Time: Fri Jan 18 19:17:57 2019

A log has been saved to sdmc:/switch/mari0/log.txt

**Comment by TurtleP** [comment]
It's not implemented because LOVE 11 removed this function. It was replaced with `love.filesystem.getDirectoryItems`.

**Comment by Noahkiq** [comment]
You may want to check out the https://github.com/stabyourself/mari0 repository as it has support for LÖVE 11.2

**Comment by TurtleP** [comment]
While this is true, iirc Mari0 still requires the use of SpriteBatches, which this still lacks. Also ImageData.
