### ISSUE TITLE
[TO DO] newSpriteBatch, getCanvas, and newImageData

### ISSUE THREAD

**Issue by TurtleP** [TurtleP/LovePotion#64]
- [ ] love.graphics.newSpriteBatch
- [ ] SpriteBatch Objects
- [ ] love.graphics.getCanvas
- [ ] love.image module
- [ ] love.image.newImageData
- [ ] ImageData objects

**Comment by XanTheDragon** [comment]
Any sort of update on this, especially for the 3DS? A game I made that I'm porting makes extensive use of this for the creation of tilesets and nine-slice GUI elements on the fly. It's very important to me personally.

**Comment by NotQuiteApex** [comment]
We've been focusing more on refactoring and trying to make function parity easier for us. We've got a semi-major update in the pipeline and a lot of smaller stuff has fallen to the wayside. It's partially implemented, but untested currently. We can try to look into doing smaller stuff before we make major changes to all the stuff behind the curtains.

**Comment by TurtleP** [comment]
Overdue reply -- We are still looking into this, although with the rewrite as-is we should be able to pinpoint doing a few of these. At least Canvases and SpriteBatches should be doable. ImageData is easier to do on Switch, as I've spoken with fincs, author of citro2d (for 3DS), and due to swizzled textures might not be *easy* or doable on that platform.
