### ISSUE TITLE
How to HTTP request?

### ISSUE THREAD

**Issue by flesnuk** [TurtleP/LovePotion#7]
I tried this, but seems  horribly wrong.
```lua
require 'socket.http'

function love.load()
  data, ok = request("http://www.google.es")
end
```
I have no idea how Lua works so I tried looking at the source code (and looking at the UDP Wiki example) but since I don't know how to check for errors and immediately crashes...

**Comment by TurtleP** [comment]
Yeah, HTTP isn't properly implemented yet. It doesn't have much of a use either, but if there *is* some use I'll fix it up (which I don't know why I haven't fixed it in the first place, but yeah..)
