### ISSUE TITLE
[Suggestion] Add asset caching

### ISSUE THREAD

**Issue by TSnake41** [TurtleP/LovePotion#80]
Add asset caching (audio, music, images) to improve RAM usage on badly designed games (games that load multiples times the same file).

This could depend on a implementation of (Compressed)ImageData, SoundData.

**Comment by TurtleP** [comment]
This won't be needed. The underlying issue with this is cached assets will never be freed from memory, even if the user kills (or nils) a variable assigned to it. It would most likely hurt more than it would help. It is ultimately up to the end user to optimize their game with caching their assets ahead of time to avoid this issue. Not even Löve itself caches data.
