### ISSUE TITLE
Check for DSP dump and tell the user if its missing

### ISSUE THREAD

**Issue by NotQuiteApex** [TurtleP/LovePotion#86]
Currently, Löve Potion 3DS will exit without warning if the user's DSP is not dumped to the `sdmc://3ds/` directory, booting back to the Homebrew Launcher. Booting the user to the errhand with an appropriate message would be preferable to the current outcome.

Something like deferred initialization of the modules done somewhere like boot.lua would help, so the modules could be called with a `pcall` and if theres an error message, everything continues as normal until the error can be processed and written (and flushed) to a file and also shown on screen.

**Comment by TurtleP** [comment]
A simple `stat` for the file should be sufficient? I’m not entirely sure. Or maybe check that SDL_mixer initialized properly. We should investigate further.

**Comment by NotQuiteApex** [comment]
I believe I found the issue. SDL_mixer doesn't properly initialize, and raises a Lua error. However, since the error is thrown before the boot script and there are no error handlers in place it prevents everything after from actually loading in Lua, allowing the application to exit quietly.
