### ISSUE TITLE
[BUG] love.graphics.draw's offset is not applied correctly.

### ISSUE THREAD

**Issue by TheV360** [TurtleP/LovePotion#87]
### **Describe the bug**
The offset should be applied after any scaling operation is done, (I think that's how it works) but instead it functions as if I just added it to the X and Y coordinates.

### **Expected behavior**
See below.

### **Relevant Code To Reproduce**
Assumptions:

* image - set to an image that should be relatively large.
* centerX and centerY - set to half the screen's pixel width and height respectively.
* width and height - equal to the image's pixel width and height.

The following code should show an image that is displayed at half its size. It should remain in the exact center of the screen.
```lua
love.graphics.draw(
	image,
	centerX + width / 2, -- compensating for offset
	centerY + height / 2,
	0,
	0.5, 0.5, -- half size
	width / 2, height / 2 -- offset
)
```
The following code should show an image that is displayed at half its size. However, its offset point is not set so it will be slightly off to the bottom right.
```lua
love.graphics.draw(
	image,
	centerX, centerY,
	0,
	0.5, 0.5 -- half size
	-- no offset
)
```
Currently, Löve Potion treats both these calls as one and the same, but in Löve2D they are very different.

### **Screenshots**
Here is a variant of the first example `love.graphics.draw` in Löve2D. Note that its pivot point is in the center:
![image](https://user-images.githubusercontent.com/25177071/61099301-d2e2ae00-a42f-11e9-88dc-1528de622852.png)

And here's the same program running on the 2DS. Note that its pivot point is in the top left rather than the middle:
![yeah](https://user-images.githubusercontent.com/25177071/61098970-cd389880-a42e-11e9-9f02-3031edb8d7fc.png)

### **System Info:**
 - System: 3DS
 - Firmware version: 11.10.0-43U
 - CFW w/ version: Luma3DS v10.0.1
 - Method of execution: Dedicated HBL app
 - Löve Potion version: https://github.com/TurtleP/LovePotion/commit/9b8fbfef4c8384b33d5114c130140eaa4d025b71 (Latest release)

**Comment by TSnake41** [comment]
According to love.graphics.draw documentation.

> Note that the offsets are applied before rotation, scaling, or shearing; scaling and shearing are applied before rotation. 

However, a different behavior than LÖVE is not expected anyway.

**Comment by TurtleP** [comment]
I think when I did this, I never applied the scalar to the offsets as necessary. This is what causes the behavior you're seeing. I'll need to look into this more when I get the chance this weekend.

**Comment by TurtleP** [comment]
Old issue, but should be fixed now.
