### ISSUE TITLE
CIA builds, tinydb support

### ISSUE THREAD

**Issue by mehlon** [TurtleP/LovePotion#92]
It would be nice if this was installable with FBI using tinydb, the titleDB clone: https://tinydb.eiphax.tech/
But FBI does not currently support installing 3dsx files in zip files, so this would require CIA builds for the 3ds. Is this possible?

**Comment by TurtleP** [comment]
I have long since dropped CIA support for Love Potion for several reasons. However, the main one is that you have no additional benefit of using it on the home screen versus the Homebrew Menu.

**Comment by NotQuiteApex** [comment]
Also, feel free to make your own games/apps made with LP into CIAs for tinydb or other places. Just LP itself should not be a CIA because it doesn't make sense for how it's designed.

**Comment by TurtleP** [comment]
@NotQuiteApex honestly CIA files have no purpose other than being on the home screen. However, I do agree if you really cared, you’d have to find on your own how to make your personal games as a CIA. 

We won’t provide support for these, however, unless it’s something related to your Lua code. Anything else is not our issue to deal with (e.g mishaps with CIA builds, etc).

Also I don’t wish for the app to be on a database such as this (or other games) as they tend to be piracy-riddled solutions for homebrew distribution.
