### ISSUE TITLE
attempt to call a nil value (in boot.lua)

### ISSUE THREAD

**Issue by matcool** [TurtleP/LovePotion#94]
I'm trying to make a really basic game just for testing and I'm getting the following error
(log.txt)
```
attempt to call a nil value

Traceback

	[string "boot"]:248: in function <[string "boot"]:235>
	[C]: in function 'xpcall'

Love Potion 1.1.0 (API 11.2.0)

Date and Time: Tue Nov 12 19:24:10 2019

A log has been saved to sdmc:/3ds/LovePotion/log.txt
```
Here's the code I'm testing with (based off nogame.lua as I couldn't find any other example)
```lua
function love.draw()
    love.graphics.setFont(love.graphics.newFont("standard"))

    love.graphics.setScreen("top")

    love.graphics.print("top", 10, 10)

    love.graphics.setScreen("bottom")

    love.graphics.print("bottom", 30, 10)

end

function love.gamepadpressed(joy, button)
    if button == love.gamepad.b or button == "start" then
        love.event.quit()
    end
end
```

**Comment by TurtleP** [comment]
Hey @matcool,
Try adding `love.load` and `love.update` functions to your main. Some other things: don't make new fonts in love.draw, as it will consume memory (a common mistake with many starting out) and you want to just say `button == "b" or button == "start"` :)

**Comment by TotalChaos05** [comment]
im having the same issue on my 3ds, it thinks setNewFont is a nil value

**Comment by AAA1exa8** [comment]
you can just use newFont and setFont

**Comment by TotalChaos05** [comment]
it segfaults with a read error(?) trying to load standard and a write error(?) trying to load custom fonts

**Comment by TurtleP** [comment]
Please don’t bump closed issues. Make a new one with relevant details and we can help you there. This original issue was solved *years* ago and doesn’t apply to whatever you are dealing with.
