### ISSUE TITLE
Implement Source:clone

### ISSUE THREAD

**Issue by XanTheDragon** [TurtleP/LovePotion#96]
LOVE recommends making use of [Source:clone](https://love2d.org/wiki/Source:clone) on duplicate audio sources since it significantly saves memory on static sound objects. Having this is a must for multi-shot audio, and implementing it in LovePotion would increase performance relating to multi-shot audio.

**Comment by NotQuiteApex** [comment]
We can look into it, but it is currently not high on our to-do list.

**Comment by TurtleP** [comment]
Should be implemented as of b9361d9 -- if there's issues, please let me know.
